
version: 2
jobs:
  build:
    working_directory: ~/django-invoices
    docker:
      - image: circleci/python:3.6.8-browsers
      - image: circleci/postgres:9.6.2
        environment: # environment variables for the Postgres container.
          POSTGRES_HOST_AUTH_METHOD: "trust"
          POSTGRES_DB: "db"
          DATABASE_URL: "postgres://postgres@postgres:5432/db"
          DEBUG: True
    steps:
      - checkout
      # - setup_remote_docker # https://circleci.com/docs/2.0/building-docker-images/
      - run:
          name: Install Python dependencies
          command: |
            python3.6 -m venv venv
            . venv/bin/activate
            pip install -r requirements.in
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{checksum "requirements.in"}}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test
            # RuntimeWarning: no database configured. Falling back to DATABASE_URL=sqlite:////home/circleci/django-invoices/data/db.sqlite3

  test-django-invoices:
    working_directory: ~/django-invoices
    machine: true

    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            docker-compose run web python manage.py test -v 3

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-django-invoices
